repos:
- hooks:
  - id: check-yaml
    exclude: helm/*
  - id: check-merge-conflict
  - exclude: README.md
    id: end-of-file-fixer
  - exclude: README.md
    id: trailing-whitespace
  - id: mixed-line-ending
  - id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
- hooks:
  - id: terraform_fmt
  - id: terraform_tflint
  - id: terraform_validate
  # - args:
  #   - -d infrastructure
  #   id: checkov
  - id: terraform_docs
  repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.44.0
- hooks:
  - id: hadolint-system
  repo: https://github.com/IamTheFij/docker-pre-commit
  rev: v2.0.0
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.13.0
- hooks:
  - id: go-fmt
  - id: golangci-lint
  - id: go-mod-tidy
  repo: git://github.com/dnephin/pre-commit-golang
  rev: v0.4.0
